"""initial schema with immutable versions and audit chain

Revision ID: 8e293da6f78f
Revises: None
Create Date: 2026-10-01 00:21:58.997903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.ddl import (
    AUDIT_FUNCTION,
    AUDIT_ROW_TRIGGER,
    AUDIT_TRUNCATE_TRIGGER,
    PROMPT_VERSION_FUNCTION,
    PROMPT_VERSION_TRIGGER,
)

# revision identifiers, used by Alembic.
revision: str = '8e293da6f78f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash'),
    sa.UniqueConstraint('seq')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_table('evaluation_datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_datasets_name'), 'evaluation_datasets', ['name'], unique=True)
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_name'), 'prompts', ['name'], unique=True)
    op.create_table('rubrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scale_min', sa.Integer(), nullable=False),
    sa.Column('scale_max', sa.Integer(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_rubric_name_version')
    )
    op.create_table('evaluation_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('expected_behavior', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'ordinal', name='uq_case_dataset_ordinal')
    )
    op.create_index(op.f('ix_evaluation_cases_dataset_id'), 'evaluation_cases', ['dataset_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('semantic_version', sa.String(length=50), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('provider_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'semantic_version', name='uq_prompt_id_semantic_version')
    )
    op.create_index('ix_only_one_active_version_per_prompt', 'prompt_versions', ['prompt_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_prompt_versions_content_hash'), 'prompt_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_prompt_versions_is_active'), 'prompt_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_prompt_versions_prompt_id'), 'prompt_versions', ['prompt_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('prompt_version_a_id', sa.UUID(), nullable=False),
    sa.Column('prompt_version_b_id', sa.UUID(), nullable=False),
    sa.Column('rubric_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('judge_provider', sa.String(length=100), nullable=False),
    sa.Column('judge_model', sa.String(length=100), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','RUNNING','COMPLETED','FAILED','CANCELLED')", name='ck_run_status'),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prompt_version_a_id'], ['prompt_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prompt_version_b_id'], ['prompt_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_dataset_id'), 'evaluation_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_prompt_version_a_id'), 'evaluation_runs', ['prompt_version_a_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_prompt_version_b_id'), 'evaluation_runs', ['prompt_version_b_id'], unique=False)
    op.create_index('ix_runs_status_created', 'evaluation_runs', ['status', 'created_at'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_run_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_case_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('winner', sa.String(length=10), nullable=True),
    sa.Column('score_a', sa.Float(), nullable=True),
    sa.Column('score_b', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('position_consistent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('COMPLETED','FAILED')", name='ck_result_status'),
    sa.CheckConstraint("winner IS NULL OR winner IN ('A','B','TIE')", name='ck_result_winner'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_result_conf'),
    sa.ForeignKeyConstraint(['evaluation_case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_run_id', 'evaluation_case_id', name='uq_result_run_case')
    )
    op.create_index(op.f('ix_evaluation_results_evaluation_case_id'), 'evaluation_results', ['evaluation_case_id'], unique=False)
    op.create_index(op.f('ix_evaluation_results_evaluation_run_id'), 'evaluation_results', ['evaluation_run_id'], unique=False)
    op.create_table('candidate_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_run_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_case_id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=True),
    sa.Column('slot', sa.String(length=1), nullable=False),
    sa.Column('prompt_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rendered_prompt', sa.Text(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slot IN ('A','B')", name='ck_output_slot'),
    sa.CheckConstraint("status IN ('COMPLETED','FAILED')", name='ck_output_status'),
    sa.ForeignKeyConstraint(['evaluation_case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['result_id'], ['evaluation_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_run_id', 'evaluation_case_id', 'slot', name='uq_output_run_case_slot')
    )
    op.create_index(op.f('ix_candidate_outputs_prompt_version_id'), 'candidate_outputs', ['prompt_version_id'], unique=False)
    op.create_index(op.f('ix_candidate_outputs_result_id'), 'candidate_outputs', ['result_id'], unique=False)
    op.create_index('ix_output_case', 'candidate_outputs', ['evaluation_case_id'], unique=False)
    op.create_table('judge_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_run_id', sa.UUID(), nullable=False),
    sa.Column('pass_index', sa.Integer(), nullable=False),
    sa.Column('swapped', sa.Boolean(), nullable=False),
    sa.Column('judge_provider', sa.String(length=100), nullable=False),
    sa.Column('judge_model', sa.String(length=100), nullable=False),
    sa.Column('rubric_id', sa.UUID(), nullable=False),
    sa.Column('rubric_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('raw_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('winner', sa.String(length=10), nullable=True),
    sa.Column('score_a', sa.Float(), nullable=True),
    sa.Column('score_b', sa.Float(), nullable=True),
    sa.Column('normalized_score_a', sa.Float(), nullable=True),
    sa.Column('normalized_score_b', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('judged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('COMPLETED','FAILED')", name='ck_judge_status'),
    sa.CheckConstraint("winner IS NULL OR winner IN ('A','B','TIE')", name='ck_judge_winner'),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['evaluation_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_id', 'pass_index', name='uq_judge_result_pass')
    )
    op.create_index(op.f('ix_judge_evaluations_evaluation_run_id'), 'judge_evaluations', ['evaluation_run_id'], unique=False)
    op.create_table('rubric_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('judge_evaluation_id', sa.UUID(), nullable=False),
    sa.Column('criterion', sa.String(length=100), nullable=False),
    sa.Column('score_a', sa.Float(), nullable=False),
    sa.Column('score_b', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['judge_evaluation_id'], ['judge_evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('judge_evaluation_id', 'criterion', name='uq_rubricscore_judge_criterion')
    )
    op.create_index(op.f('ix_rubric_scores_judge_evaluation_id'), 'rubric_scores', ['judge_evaluation_id'], unique=False)
    # ### end Alembic commands ###

    # Database-level guarantees that SQLAlchemy metadata cannot express:
    # prompt_versions content is immutable; audit_logs is append-only.
    for statement in (
        PROMPT_VERSION_FUNCTION,
        PROMPT_VERSION_TRIGGER,
        AUDIT_FUNCTION,
        AUDIT_ROW_TRIGGER,
        AUDIT_TRUNCATE_TRIGGER,
    ):
        op.execute(statement)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_no_truncate ON audit_logs")
    op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_no_update_delete ON audit_logs")
    op.execute("DROP FUNCTION IF EXISTS audit_logs_append_only")
    op.execute("DROP TRIGGER IF EXISTS trg_prompt_versions_immutable ON prompt_versions")
    op.execute("DROP FUNCTION IF EXISTS prompt_versions_enforce_immutability")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rubric_scores_judge_evaluation_id'), table_name='rubric_scores')
    op.drop_table('rubric_scores')
    op.drop_index(op.f('ix_judge_evaluations_evaluation_run_id'), table_name='judge_evaluations')
    op.drop_table('judge_evaluations')
    op.drop_index('ix_output_case', table_name='candidate_outputs')
    op.drop_index(op.f('ix_candidate_outputs_result_id'), table_name='candidate_outputs')
    op.drop_index(op.f('ix_candidate_outputs_prompt_version_id'), table_name='candidate_outputs')
    op.drop_table('candidate_outputs')
    op.drop_index(op.f('ix_evaluation_results_evaluation_run_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_evaluation_case_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index('ix_runs_status_created', table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_prompt_version_b_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_prompt_version_a_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_dataset_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_prompt_versions_prompt_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_is_active'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_content_hash'), table_name='prompt_versions')
    op.drop_index('ix_only_one_active_version_per_prompt', table_name='prompt_versions', postgresql_where=sa.text('is_active = true'))
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_evaluation_cases_dataset_id'), table_name='evaluation_cases')
    op.drop_table('evaluation_cases')
    op.drop_table('rubrics')
    op.drop_index(op.f('ix_prompts_name'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_evaluation_datasets_name'), table_name='evaluation_datasets')
    op.drop_table('evaluation_datasets')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
